//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductsName { get; set; }
        public int CustomerID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SubcategoryID { get; set; }
        public string ProductImage { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Chair Chair { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual HomeTheater HomeTheater { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Table Table { get; set; }
        public virtual TV TV { get; set; }
    }
}
