//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>https://localhost:44363/Models/User.cs
//------------------------------------------------------------------------------

namespace JooleWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage ="this field is required")]
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "this field is required")]
        public string Password { get; set; }
        public string Avatan { get; set; }
        public byte Credentials { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
